apiVersion: v1
kind: Service
metadata:
  labels:
    app: facebook-dpa
  name: facebook-dpa
spec:
  type: LoadBalancer
  ports:
    - port: 50053
      name: http-port
      targetPort: 50053
  selector:
    app: facebook-dpa